### ISSUE TITLE
Problème importation Win10toast

### ISSUE THREAD

**Issue by Kripiti** [qaniere/Kripto#8]
L'API Windows pour les notifications sur Windows 10 ne fonctionne pas de manière stable quand on réussit à l'installer (ce qui n'est pas gagné non plus)

Windows 10 10.0.18362

**Comment by qaniere** [comment]
La fonctionnalité va être temporairement désactivée, puis remplacée par des fenêtres topLevel

**Comment by qaniere** [comment]
L'API étant plus stable que ce que je pensais, je vais simplement la rendre non-obligatoire pour les machines non équipées de Windows 10

**Comment by qaniere** [comment]
Problème réglé dans le dernier commit, les notifications sont de retour !
